id: 178207ec-417b-4b9c-8176-c8401462c752
version: 7
vcShouldKeepItemLegacyProdMachine: false
name: Linux MTU Check
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 5e785fa3-f67b-4471-80e0-d596752c92fc
    type: start
    task:
      id: 5e785fa3-f67b-4471-80e0-d596752c92fc
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "1":
    id: "1"
    taskid: cb7f08fc-1108-4c28-824a-16497acc5f9f
    type: regular
    task:
      id: cb7f08fc-1108-4c28-824a-16497acc5f9f
      version: -1
      name: ip addr show
      description: Execute commands using Netmiko
      script: '|||netmiko-cmds'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      cmds:
        simple: ip addr show
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "2":
    id: "2"
    taskid: 7be26afa-3146-49be-8e49-15515577cd96
    type: condition
    task:
      id: 7be26afa-3146-49be-8e49-15515577cd96
      version: -1
      name: Is MTU for the eth0 interface greater than 5000?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "4"
      "yes":
      - "3"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: greaterThan
          left:
            value:
              simple: MTU
            iscontext: true
          right:
            value:
              simple: "5000"
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "3":
    id: "3"
    taskid: 4d5ca94b-8137-4185-8e4b-78f2aa063b16
    type: title
    task:
      id: 4d5ca94b-8137-4185-8e4b-78f2aa063b16
      version: -1
      name: Fin
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 895
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "4":
    id: "4"
    taskid: bf3ef2e8-58cd-4d5a-8a90-453915320e8f
    type: collection
    task:
      id: bf3ef2e8-58cd-4d5a-8a90-453915320e8f
      version: -1
      name: Send Data Collection Task
      type: collection
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    message:
      to: null
      subject: null
      body: null
      methods: []
      format: ""
      bcc: null
      cc: null
      timings:
        retriescount: 2
        retriesinterval: 360
        completeafterreplies: 1
        completeafterv2: true
        completeaftersla: false
    form:
      questions:
      - id: "0"
        label: ""
        labelarg:
          simple: What should the MTU be increased to?
        required: false
        gridcolumns: []
        defaultrows: []
        type: shortText
        options: []
        optionsarg: []
        fieldassociated: ""
        placeholder: ""
        tooltip: ""
        readonly: false
      title: MTUSurvey
      description: ""
      sender: ""
      expired: false
      totalanswers: 0
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "5":
    id: "5"
    taskid: ac7bf9b7-e7cf-4871-852d-ef2ae9f22aaa
    type: regular
    task:
      id: ac7bf9b7-e7cf-4871-852d-ef2ae9f22aaa
      version: -1
      name: Set MTU
      description: Set a value in context under the key you entered.
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      key:
        simple: MTU
      value:
        complex:
          root: Netmiko
          accessor: Output
          transformers:
          - operator: substringFrom
            args:
              from:
                value:
                  simple: eth0
          - operator: substringFrom
            args:
              from:
                value:
                  simple: 'mtu '
          - operator: substringTo
            args:
              to:
                value:
                  simple: ' '
          - operator: toUpperCase
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 910,
        "width": 492.5,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
